### PR TITLE
Add subdomain to Reddit endpoint to avoid redirect

### PR DESCRIPTION
**Pull request by GalenReich**
Reddit has a permanent redirect from reddit.com to www.redit.com, this PR tweaks the endpoint to avoid this redirect.

image

### CODE REVIEW

**Comment by GalenReich** [comment]
For interest, I noticed this when trying to run rpst within a browser, because the 301 response does not include a `access-control-allow-origin` header, so my request failed with a CORS error.

**Comment by rly0nheart** [comment]
My bad😅, I will recompile the GUI and push a new release in a few hours.

**Comment by GalenReich** [comment]
Absolutely no worries at all! I'm trying to get a look at all the codebase for lots of the Bellingcat public tools, so you might see a few different things popping up from me 😂 Would be great to have a chat with you actually - I'll reach out separately 👍

**Comment by rly0nheart** [comment]
> Absolutely no worries at all! I'm trying to get a look at all the codebase for lots of the Bellingcat public tools, so you might see a few different things popping up from me 😂 Would be great to have a chat with you actually - I'll reach out separately 👍

Haha no problem! Miguel told me about you, I'll be looking forward to it

**Pull request merged**
